package filter;

public interface BPEstimationFilter_BAK {
	/*
	 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
	 *
	 * Generated by MATLAB(R) 7.3 and the Signal Processing Toolbox 6.6.
	 *
	 * Generated on: 29-Nov-2008 21:07:26
	 *
	 */

	/*
	 * Discrete-Time IIR Filter (real)
	 * -------------------------------
	 * Filter Structure    : Direct-Form II, Second-Order Sections
	 * Number of Sections  : 12
	 * Stable              : Yes
	 * Linear Phase        : No
	 *
	 * Implementation Cost
	 * Number of Multipliers : 36
	 * Number of Adders      : 36
	 * Number of States      : 24
	 * MultPerInputSample    : 36
	 * AddPerInputSample     : 36
	 */
	
	
	public static final double[][] NUM = {
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
		  {
	           1,                 0,                -1 
		  },
	};		

	
	public  static final double[][] DEN = {
	  {
	                   1,   -1.994823427912,   0.9948381126604 
	  },	  
	  {
	                   1,   -1.992854499296,   0.9928725030478 
	  },	  
	  {
	                   1,   -1.976686559444,   0.9772294108993 
	  },	  
	  {
	                   1,   -1.970539810868,   0.9710086828872 
	  },	 
	  {
	                   1,    -1.99931996108,   0.9993311072135 
	  },	  
	  {
	                   1,   -1.997951331006,   0.9979629698704 
	  },	  
	  {
	                   1,   -1.990638649817,   0.9906617380582 
	  },	 
	  {
	                   1,   -1.984862931726,   0.9854597596802 
	  },	  
	  {
	                   1,   -1.967026303847,   0.9674076722514 
	  },	  
	  {
	                   1,   -1.966416232286,    0.966713186852 
	  },	  
	  {
	                   1,     -1.9964825809,   0.9964953147924 
	  },	  
	  {
	                   1,   -1.994363879411,    0.994990507163 
	  },	  
	};
	
	public static final double[] GAIN = {
		0.010808044195775439,                                         
		0.010792959640574789,                                         
		0.010829485356737169,                                         
		0.010808044195775439,                                         
		0.010885633559857381,                                         
		0.010855919978419726,                                         
		0.010785176067561648,                                         
		0.010855919978419726,                                         
		0.010792959640574789,                                         
		0.010785176067561648,                                         
		0.010829485356737169,                                         
		0.010885633559857381,	
	};	 

}
