package filter;

public class BPEstimationFilter {
	
	/*
	 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
	 *
	 * Generated by MATLAB(R) 7.3 and the Signal Processing Toolbox 6.6.
	 *
	 * Generated on: 08-Dec-2008 21:09:54
	 *
	 */

	/*
	 * Discrete-Time IIR Filter (real)
	 * -------------------------------
	 * Filter Structure    : Direct-Form I
	 * Numerator Length    : 5
	 * Denominator Length  : 5
	 * Stable              : Yes
	 * Linear Phase        : No
	 *
	 * Implementation Cost
	 * Number of Multipliers : 7
	 * Number of Adders      : 6
	 * Number of States      : 8
	 * MultPerInputSample    : 7
	 * AddPerInputSample     : 6
	 */

	public static final double[] NUM = {
		  0.0001172996976609,                 0,-0.0002345993953218,                 0,
		  0.0001172996976609
	};
	
	public static final double[] DEN = {
        1,     -3.9689665722,     5.90753792288,    -3.90817356576,
        0.9696022220078
	};
}
